<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="5" hostname="DESKTOP-8A29R4R" name="org.rerun.RerunAutomationSample" tests="10" failures="1" timestamp="2021-04-10T11:08:09 IST" time="0.033" errors="0">
  <testcase name="tc24" time="0.007" classname="org.rerun.RerunAutomationSample">
    <skipped/>
  </testcase> <!-- tc24 -->
  <system-out/>
  <testcase name="tc21" time="0.001" classname="org.rerun.RerunAutomationSample"/>
  <system-out/>
  <testcase name="tc24" time="0.006" classname="org.rerun.RerunAutomationSample">
    <skipped/>
  </testcase> <!-- tc24 -->
  <system-out/>
  <testcase name="tc24" time="0.002" classname="org.rerun.RerunAutomationSample">
    <skipped/>
  </testcase> <!-- tc24 -->
  <system-out/>
  <testcase name="tc20" time="0.009" classname="org.rerun.RerunAutomationSample"/>
  <system-out/>
  <testcase name="tc25" time="0.001" classname="org.rerun.RerunAutomationSample"/>
  <system-out/>
  <testcase name="tc24" time="0.001" classname="org.rerun.RerunAutomationSample">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at org.rerun.RerunAutomationSample.tc24(RerunAutomationSample.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tc24 -->
  <system-out/>
  <testcase name="tc24" time="0.002" classname="org.rerun.RerunAutomationSample">
    <skipped/>
  </testcase> <!-- tc24 -->
  <system-out/>
  <testcase name="tc24" time="0.003" classname="org.rerun.RerunAutomationSample">
    <skipped/>
  </testcase> <!-- tc24 -->
  <system-out/>
  <testcase name="tc22" time="0.001" classname="org.rerun.RerunAutomationSample"/>
  <system-out/>
</testsuite> <!-- org.rerun.RerunAutomationSample -->
